name: Update

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Waiting for 200 from the Netlify Preview
      uses: jakepartusch/wait-for-netlify-action@v1.2
      id: spacejellydev
      with:
        site_name: "spacejellydev"
        max_timeout: 60

    - uses: colbyfayock/applitools-eyes-action@main
      with:
        APPLITOOLS_API_KEY: ${{secrets.APPLITOOLS_API_KEY}}
        appName: Space Jelly Shop
        baseUrl: ${{ steps.spacejellydev.outputs.url }}
        
    - name: consolelog
      run: |
        echo ${{ steps.spacejellydev.outputs }}
        
       
