name: Thank You

on:
  pull_request:
    types: [opened]

jobs:
  thanks:
    runs-on: ubuntu-latest
    steps:
      - uses: colbyfayock/gif-or-treat@main
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          TENOR_TOKEN: ${{secrets.TENOR_TOKEN}}
